import Head from 'next/head'
import Header from '@/components/Header'
import Image from 'next/image'
import { GiHamburgerMenu } from 'react-icons/Gi'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Icon } from '@/components/utils'
import Link from 'next/link'
import { useEffect } from 'react'
import { useState } from 'react'
import Row from '@/components/ROws'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [dropdownOpen, setDropdownOpen] = useState(false);

  function toggleDropdown() {
    setDropdownOpen(!dropdownOpen);
  }
  useEffect(() => {

    function ife() {
      const script = document.createElement("script");

      script.src = "https://cdn.gtranslate.net/widgets/latest/dropdown.js";
      script.async = true;
      document.body.appendChild(script);
    }
    ife();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <div className='fixed w-[100%] mb-32'>
          <header className='bg-yellow-600 text-white flex justify-end   '>
            <p className='px-4'>Need help?</p>
            <p className='px-4'>support@fashy.ng</p>
            {/* <div className="gtranslate_wrapper text-black w-[10px] h-1" style={{ paddingLeft: "20px" }}></div> */}
            <p className='px-4'>Contact</p>
          </header>
          <Header />
          </div>
          <main className='w2 w-[100%] h-[50%]'>
            <div>


              <div >
               


              </div>
              <div className='pt-[200px]'>
              <div className='text-yellow-600 w-[40%] glass px-5 py-5 relative mb-[20px] text-[18px] z-10'>
                <h1 className='text-[3rem] font-bold font-["Clash Display"]'>Custom Suits</h1>
                <p className='text-[2rem] py-3'>from 199€</p>
                <p className=' font-lato text-[1rem] py-1'>★ ★ ★ ★ ★ 285 Reviews</p>
                <p className=' font-["Clash Display"] text-[1rem] pb-3'>100% Made to Measure Suits</p>
                <p>Are you looking for a custom suit that will make you look stunning and express your personal style to the fullest? Hockerty has the answer! Our suits are not only high-quality but they are also hand tailored to your measurements. Choose from more than 150 fabrics and various details and design your own outfit. We guarantee the perfect fit of your tailor-made Hockerty suit.</p>

                <button className='rounded-3xl text-yellow-600 border-2 px-5 py-2'>Contact us</button>
              </div>
              <p>


              </p>
              </div>
            </div>
          </main>
          <Row/>
          
        </section>
      </main>


    </>
  )
}
